[tool.poetry]
name = "deafear"
version = "0.1.0"
description = ""
authors = ["hoangtrungkien2109 <hoangtrungkien2109@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
